In [1]:
import numpy as np

## Q1c

In [4]:
p = np.array([[0.9, 0.1, 0], [0, 0.75, 0.25], [0.5, 0, 0.5]])
n = 50
print(np.linalg.matrix_power(p, n))

[[0.625 0.25  0.125]
 [0.625 0.25  0.125]
 [0.625 0.25  0.125]]


## Q2d

In [5]:
q = np.array([[0.5, 0.5, 0, 0, 0, 0], [1.0/3, 0, 1.0/3, 0, 1.0/3, 0], [0, 0, 0.25, 0.75, 0, 0], [0, 0, 1, 0, 0, 0], [0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 1, 0]])
k = 20
m = 21
print(np.linalg.matrix_power(q,k))
print(np.linalg.matrix_power(q, m))

[[1.35702571e-03 9.31110517e-04 2.85444344e-01 2.13411588e-01
  3.12017735e-01 1.86838197e-01]
 [6.20740345e-04 4.25915191e-04 2.84721745e-01 2.14754927e-01
  6.22793989e-02 4.37197273e-01]
 [0.00000000e+00 0.00000000e+00 5.72787662e-01 4.27212338e-01
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 5.69616450e-01 4.30383550e-01
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  1.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 1.00000000e+00]]
[[9.88883026e-04 6.78512854e-04 2.85083044e-01 2.14083258e-01
  1.87148567e-01 3.12017735e-01]
 [4.52341903e-04 3.10370172e-04 2.86077335e-01 2.13541309e-01
  4.37339245e-01 6.22793989e-02]
 [0.00000000e+00 0.00000000e+00 5.70409253e-01 4.29590747e-01
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 5.72787662e-01 4.27212338e-01
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.